version: "3"

services:
  django:
    build: ./carent
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./carent/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgresql_dev/data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
