# Generated by Django 3.2.12 on 2022-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание условия')),
            ],
            options={
                'verbose_name': 'Условие проката',
                'verbose_name_plural': 'Условия проката',
            },
        ),
    ]
