# Generated by Django 3.2.12 on 2022-04-02 13:01

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название автомобиля')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('discount', models.PositiveSmallIntegerField(validators=[cars.models.validate_discount], verbose_name='Скидка')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand', verbose_name='Марка')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
        migrations.CreateModel(
            name='Сharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название характеристика')),
                ('type', models.CharField(choices=[('string', 'Строка'), ('text', 'Текст'), ('boolean', 'Да/Нет'), ('datetime', 'Дата и время'), ('date', 'Дата'), ('integer', 'Целое число'), ('decimal', 'Число с плавающей точкой')], max_length=255, verbose_name='Тип характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='СharacteristicCarValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение характеристики')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Машина')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.сharacteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Значение характеристики автомобиля',
                'verbose_name_plural': 'Значения характеристик автомобилей',
                'unique_together': {('car', 'characteristic')},
            },
        ),
    ]
