# Generated by Django 3.2.12 on 2022-04-04 10:51

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default='1', upload_to=cars.models.Car.upload_to, verbose_name='Фотография'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='сharacteristic',
            name='type',
            field=models.CharField(choices=[('string', 'Строка'), ('boolean', 'Да/Нет'), ('date', 'Дата'), ('integer', 'Целое число'), ('decimal', 'Число с плавающей точкой')], max_length=255, verbose_name='Тип характеристики'),
        ),
        migrations.AlterField(
            model_name='сharacteristiccarvalue',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение характеристики'),
        ),
    ]
