# Generated by Django 3.2.12 on 2022-04-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20220404_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='сharacteristiccarvalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='сharacteristiccarvalue',
            name='car',
        ),
        migrations.RemoveField(
            model_name='сharacteristiccarvalue',
            name='characteristic',
        ),
        migrations.DeleteModel(
            name='Сharacteristic',
        ),
        migrations.DeleteModel(
            name='СharacteristicCarValue',
        ),
    ]
