# Generated by Django 3.2.12 on 2022-04-10 18:17

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220406_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cars.models.CarImage.upload_to, verbose_name='Фотография')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car', verbose_name='Машина')),
            ],
            options={
                'verbose_name': 'Фото машины',
                'verbose_name_plural': 'Фото машин',
            },
        ),
    ]
