# Generated by Django 3.2.12 on 2022-04-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('eav', '0008_auto_20220407_1753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='value',
            unique_together={('entity_id', 'entity_ct', 'attribute')},
        ),
    ]
